# get all user
GET http://localhost:5000/api/user

###
# get a user
GET http://localhost:5000/api/user/62b782e2bbaf7ae78c8663e6
Content-Type: application/json


### save a user
POST http://localhost:5000/api/user
Content-Type: application/json

{
    "name":"user2",
    "email":"user2@contoh.com",
    "password":"123"

}

### update user
PATCH  http://localhost:5000/api/user/62b782e2bbaf7ae78c8663e6
Content-Type: application/json

{
    "name":"user1",
    "email":"user1@gmail.com"
    

}
### delete user
DELETE   http://localhost:5000/api/user/62b77b11713c09270af5ad7e
Content-Type: application/json


